### ISSUE TITLE
Photo Year Navigation 

### ISSUE THREAD

**Issue by AudreyZone4** [kevinli96/BCG-Zone-4#8]
Is it feasible to have the Year menu navigation open at the year heading rather than the first photo?  e.g. when you click on the 2015, it opens at the first photo and the “2015 Champions” title does not display so it is a bit confusing.

**Comment by kevinli96** [comment]
The year scroll now goes to the heading of each year - I had to add some extra spacing so it doesn't look as ideal right now, but I think it will manage. Thinking of a way to work around this. 

I've also added the year scroll to the assorted photos page.

Just a note that past a certain screen width (1000px right now), the year scroll disappears. This is because on mobile and smaller width screens, the display becomes very crammed with the vertical year scroll on the left. I'm going to do more research on how to better position the scrolls, and to see if going horizontally can be an option.
